#include "WebUI.h"
#include <WiFi.h>
#include <WebServer.h>
#include "Tunings.h"
#include "HAL.h"

WebServer server(80);

const char* html_page = R"(
<!DOCTYPE html>
<html>
<head>
    <title>GuitarBot Control</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <style>
        body { font-family: sans-serif; text-align: center; background: #222; color: #fff; margin: 0; padding: 20px; }
        h1 { color: #fca311; margin-bottom: 30px; }
        .card { background: #333; margin: 10px; padding: 20px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0,0,0,0.5); }
        .row { display: flex; flex-wrap: wrap; justify-content: center; max-width: 1000px; margin: 0 auto; }
        .col { flex: 1; min-width: 320px; display: flex; flex-direction: column; }
        button { background: #14213d; color: white; border: none; padding: 12px; font-size: 15px; margin: 5px; border-radius: 5px; cursor: pointer; transition: 0.2s; }
        button:hover { background: #fca311; color: black; }
        #tuningLabel { font-size: 20px; font-weight: bold; color: #fca311; }
        .grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; }
        .chord-list { display: flex; flex-direction: column; gap: 8px; }
    </style>
</head>
<body>
    <h1>🎸 GuitarBot Command Center</h1>
    
    <div class="card">
        <h2>1. Global Tuning</h2>
        <p>Current: <span id='tuningLabel'>Standard</span></p>
        <button onclick="setTuning(0)">Standard</button>
        <button onclick="setTuning(1)">Open E</button>
        <button onclick="setTuning(2)">Open G</button>
        <button onclick="setTuning(3)">Drop D</button>
    </div>

    <div class="row">
        <div class="col">
            <div class='card' style="height: 100%;">
                <h2>2. Manual Strings</h2>
                <div class="grid-3">
                    <button onclick="pluck(0)" style="background:#e63946">Corda 1</button>
                    <button onclick="pluck(1)" style="background:#e63946">Corda 2</button>
                    <button onclick="pluck(2)" style="background:#e63946">Corda 3</button>
                    <button onclick="pluck(3)" style="background:#457b9d">Corda 4</button>
                    <button onclick="pluck(4)" style="background:#457b9d">Corda 5</button>
                    <button onclick="pluck(5)" style="background:#457b9d">Corda 6</button>
                </div>
            </div>
        </div>

        <div class="col">
            <div class='card' style="height: 100%;">
                <h2>3. Possible Chords</h2>
                <div id="chordContainer" class="chord-list">
                    <!-- Buttons generated by JS -->
                </div>
                <div id="statusMsg" style="color: #fca311; margin-top: 15px; font-weight: bold; min-height: 24px;"></div>
            </div>
        </div>
    </div>

    <script>
        const chordMap = {
            0: [], // Standard: No chords
            1: [ {f:0, n:"E Major"}, {f:1, n:"F Major"}, {f:2, n:"F# Major"}, {f:3, n:"G Major"}, {f:4, n:"G# Major"} ],
            2: [ {f:0, n:"G Major"}, {f:2, n:"A Major"}, {f:4, n:"B Major"} ],
            3: [ {f:0, n:"D5 Power"}, {f:1, n:"Eb5 Power"}, {f:2, n:"E5 Power"}, {f:3, n:"F5 Power"}, {f:4, n:"F#5 Power"} ]
        };

        function showMsg(text) {
            const el = document.getElementById('statusMsg');
            el.innerText = text;
            el.style.opacity = 1;
            setTimeout(() => { el.style.opacity = 0.5; }, 1000);
            setTimeout(() => { el.innerText = ''; }, 2500);
        }

        function setTuning(idx) {
            fetch('/set?t=' + idx)
                .then(response => response.text())
                .then(text => {
                    document.getElementById('tuningLabel').innerText = text;
                    updateButtons(idx);
                    showMsg("Tuning: " + text);
                });
        }
        
        function updateButtons(tIdx) {
            const container = document.getElementById('chordContainer');
            container.innerHTML = "";
            const chords = chordMap[tIdx];
            
            if (chords.length === 0) {
                container.innerHTML = "<p style='color:#888'>No compatible chords for this tuning.</p>";
                return;
            }

            chords.forEach(c => {
                const btn = document.createElement("button");
                btn.innerText = "Trast " + c.f + ": " + c.n;
                btn.onclick = () => moveBar(c.f, c.n);
                container.appendChild(btn);
            });
        }
        
        function pluck(s) { fetch('/pluck?s=' + s); }
        function moveBar(f, name) { 
            fetch('/bar?f=' + f);
            showMsg("Bar to Trast " + f + " (" + name + ")");
        }
        
        window.onload = function() { updateButtons(0); };
    </script>
</body>
</html>
)";

void handleRoot() {
    server.send(200, "text/html", html_page);
}

void handleSet() {
    if (server.hasArg("t")) {
        int t = server.arg("t").toInt();
        TuningManager::setTuning((TuningType)t);
        server.send(200, "text/plain", TuningManager::getName());
    } else {
        server.send(400, "text/plain", "Missing arg");
    }
}

// Quick manual test endpoints
void handlePluck() {
    if (server.hasArg("s")) {
        int s = server.arg("s").toInt();
        // Trigger via HAL directly
        // Note: For real sound we might want to ensure the Bar is correct, 
        // but for a raw motor test, direct HAL is better.
        HAL::pluckString(s);
        server.send(200, "text/plain", "Plucked");
    }
}

void handleBar() {
    if (server.hasArg("f")) {
        int f = server.arg("f").toInt();
        HAL::setGlobalFret(f);
        server.send(200, "text/plain", "Bar Moved");
    }
}

void WebUI::init() {
    // Create Access Point
    WiFi.softAP("GuitarBot_Setup", "12345678");
    Serial.println("WebUI: AP Started. IP: 192.168.4.1");
    
    server.on("/", handleRoot);
    server.on("/set", handleSet);
    server.on("/pluck", handlePluck);
    server.on("/bar", handleBar);
    
    server.begin();
}

void WebUI::loop() {
    server.handleClient();
}
